use crate::Grid;

// TODO: these grids could be generated at compile time instead of using 'new'
pub fn lookup( name: &str ) -> Grid {
    const X : u32 = 123456789;
    match name {
        "top-row-only" => Grid::new( &[
            1, 2, 3, X, 5, 6, 7, 8, 9,
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X] ),

        "invalid" => Grid::new( &[
            9, 6, X, 9, 2, X, 8, 1, X,
            X, 2, 1, 4, X, X, X, X, X,
            X, X, 5, X, X, 3, 2, X, X,
            X, X, 2, X, X, 4, X, 3, 9,
            X, 3, 8, X, X, X, 1, 4, X,
            4, 9, X, 3, X, X, 6, X, X,
            X, X, 6, 7, X, X, 9, X, X,
            X, X, X, X, X, 9, 4, 7, X,
            X, 1, 9, X, 4, X, X, 8, 6] ),

        "easy" => Grid::new( &[
            9, 6, X, X, 2, X, 8, 1, X,
            X, 2, 1, 4, X, X, X, X, X,
            X, X, 5, X, X, 3, 2, X, X,
            X, X, 2, X, X, 4, X, 3, 9,
            X, 3, 8, X, X, X, 1, 4, X,
            4, 9, X, 3, X, X, 6, X, X,
            X, X, 6, 7, X, X, 9, X, X,
            X, X, X, X, X, 9, 4, 7, X,
            X, 1, 9, X, 4, X, X, 8, 6] ), // 34 hints

        "medium" => Grid::new( &[
            2, X, 7, X, X, X, X, X, X,
            X, X, 5, 6, X, 7, X, X, 4,
            8, X, X, X, X, X, 1, X, X,
            X, 1, X, X, 7, 9, 6, X, 8,
            X, 5, X, X, 6, 2, X, 4, X,
            X, X, X, 5, 3, X, X, X, X,
            7, X, 1, X, X, 5, X, X, X,
            X, X, X, X, 2, 6, 8, X, 5,
            X, X, 6, 8, X, 1, 4, X, X] ), // 30 hints (generated by sudoku.com)

        "hard" => Grid::new( &[
            6, X, X, X, X, X, X, X, X,
            X, X, 1, X, X, X, 4, 6, X,
            5, X, X, X, X, 3, 2, X, X,
            X, X, X, X, 8, X, X, X, X,
            X, 9, 6, 4, X, X, X, X, X,
            2, X, 4, X, 1, X, 5, X, 3,
            X, X, 8, X, X, X, X, 3, X,
            X, X, 3, 2, 4, X, X, 1, X,
            X, X, X, X, X, 8, 6, X, 2] ), // 25 hints (generated by sudoku.com)

        "expert" => Grid::new( &[
            X, X, X, X, X, 7, 9, 1, X,
            X, X, X, X, 1, X, X, X, X,
            X, 2, X, X, 9, X, 5, X, X,
            X, 6, X, X, X, X, X, 7, X,
            X, X, X, 4, X, 6, X, X, 8,
            X, X, 5, X, X, X, X, X, 2,
            7, X, X, 3, X, X, X, X, X,
            2, X, X, 7, 8, X, X, X, X,
            9, 5, 1, X, X, X, X, X, X] ), // 22 hints (generated by sudoku.com)

        _ => Grid::new( &[
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X,
            X, X, X, X, X, X, X, X, X] )
    }
}
